language: python
python:
  - 2.7
  - 2.7.8
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy3

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage
  - pip install coveralls

script:
  - coverage run --srouce=PhloxAR setup.py test

after_success:
  - coveralls

branches:
  only:
    - master